name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Ensure each Docker build uses the correct directory
    - name: Build and push Auth Service Image
      run: |
        docker build -t chandima99/auth-service:${{ github.sha }} ./auth-service
        docker push chandima99/auth-service:${{ github.sha }}

    # Repeat for other services, ensuring each directory is correct
    - name: Build and push Add Service Image
      run: |
        docker build -t chandima99/add-service:${{ github.sha }} ./add-service
        docker push chandima99/add-service:${{ github.sha }}

    # Add the local-api-gateway if there's a specific directory for it
    - name: Build and push local-api-gateway Image
      run: |
        docker build -t chandima99/local-api-gateway:${{ github.sha }} ./local-api-gateway
        docker push chandima99/local-api-gateway:${{ github.sha }}

# Add other services similarly
