name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, add-service, user-service, review-service, deliver-service, ordermanagement-service, local-api-gateway]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker Image
      run: |
        docker build -t chandima99/${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}
        docker push chandima99/${{ matrix.service }}:${{ github.sha }}
